fun main() {
    var circle = Circle(11f, 1f, 1f)
    println(circle.area())
    var circle2 = Circle(circle)
    println(circle2.area())
    circle.resize(10)
    println(circle.area())
    print(circle.x)
    print(' ')
    println(circle.y)
    circle.rotate(RotateDirection.Clockwise, 3, 3)
    print(circle.x)
    print(' ')
    println(circle.y)

    var square1 = Square()
    var square2 = Square(10f, 3f, 4f)
    println(square1.area())
    println(square2.area())
    square1.resize(10)
    println(square1.area())
    print(square2.x)
    print(' ')
    println(square2.y)
    square2.rotate(RotateDirection.Clockwise, 3, 3)
    print(square2.x)
    print(' ')
    println(square2.y)
    print(square2.x)
    print(' ')
    println(square2.y)
    var r2 = Rect(1f, 3f, 10f, 4f)
    println("Rotation:")
    print(r2.x)
    print(' ')
    print(r2.y)
    print(r2.width)
    println(r2.height)
    r2.rotate(RotateDirection.Clockwise, 3, 3)
    print(r2.x)
    print(' ')
    print(r2.y)
    print(" width=")
    print(r2.width)
    print(" height=")
    println(r2.height)
    r2.rotate(RotateDirection.Clockwise, 3, 3)
    print(r2.x)
    print(' ')
    print(r2.y)
    print(" width=")
    print(r2.width)
    print(" height=")
    println(r2.height)
    r2.rotate(RotateDirection.Clockwise, 3, 3)
    print(r2.x)
    print(' ')
    print(r2.y)
    print(r2.width)
    println(r2.height)
    r2.rotate(RotateDirection.Clockwise, 3, 3)
    print(r2.x)
    print(r2.y)
    print(r2.width)
    println(r2.height)
}